[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.partitions = partitions.csv
lib_deps =
  adafruit/Adafruit SHT4x Library
  adafruit/Adafruit BME680 Library
  bblanchon/ArduinoJson
  knolleary/PubSubClient
build_flags =
  -D CORE_DEBUG_LEVEL=3
